### ISSUE TITLE
App looks great, but what is user pass?

### ISSUE THREAD

**Issue by Povezi** [dnbn/smbtv#1]
When I connect to my Sony Bravia with your app installed and listening on port 2445, it looks for user/pass? Also, can I contribute English translation?

**Comment by dnbn** [comment]
Sure you can.
There is no authentification, just choose "anonymous connexion" or
something similar.

2017-03-19 22:24 GMT+01:00 Povezi <notifications@github.com>:

**Comment by Povezi** [comment]
Thnx for super fast answer! I have tried loging as guest (from my mac) but I cannot connect...

Is there any way to add user/pass to application code/settings?

**Comment by dnbn** [comment]
Loging as guest is supposed to work, at least it works fine on my linux.
I started working on adding user/pass from the application some times ago but haven't finished the dev. I'll continue in the next few weeks if I have free time.

**Comment by Povezi** [comment]
Maybe it is OSX related, I'll try from linux..

on osx, it cannot see shares:

# smbutil view -a //192.168.60.49:2445/1ED9-0914
Share                                           Type    Comments
-------------------------------

0 shares listed

**Comment by Povezi** [comment]
Ha! Maybe it is related to this:
https://community.alfresco.com/thread/174202-alfresco-32-cant-mount-cifs-drives-under-osx

**Comment by dnbn** [comment]
Interesting, but I hope it will works with login/password once implemented because I have no idea.

On linux :
smbclient -p 2445 //192.168.XX.XX/sharename/ -U guest%

**Comment by Povezi** [comment]
Trying this on raspberry, and it works with -N parameter !

# smbclient -p 2445 -N //192.168.60.49/1ED9-0914/
Server does not support EXTENDED_SECURITY  but 'client use spnego = yes and 'client ntlmv2 auth = yes'
Anonymous login successful
Domain=[MYDOMAIN] OS=[Java] Server=[Alfresco CIFS Server 5.0.0]
smb: \> ls
---

have to figure how to connect from osx ;)

**Comment by Povezi** [comment]
Thank you for your time, I'll write if I solve OSX connection issue...

**Comment by dnbn** [comment]
No problem, thanks for the feedback
