### ISSUE TITLE
Write permission

### ISSUE THREAD

**Issue by boulate** [dnbn/smbtv#2]
Hi, and thank you for this app !

Is there a way to enable SMB write permission on the shared folders ? (without having to root the android TV box)

**Comment by dnbn** [comment]
Hi, [WRITE_EXTERNAL_STORAGE](https://developer.android.com/reference/android/Manifest.permission.html#WRITE_EXTERNAL_STORAGE) permission is enabled. So you should be able to write in "/storage/emulated/0/..." without having to root your box.
