### ISSUE TITLE
how it works,started and cannot find server with ES explorer

### ISSUE THREAD

**Issue by huanyuan** [dnbn/smbtv#4]

**Comment by dnbn** [comment]
Are you root on the server device ?
If you are root you can change the port numbers in settings to use standard ports (you'll have to replace 2XXX by XXX) and you will find ther server in ES explorer.

If you are not root and use ports 2XXX, you will have to connect the server by indicating the port number. On linux :  smbclient -p 2445 //192.168.XX.XX/sharename/ -U guest%
It's not possible on windows, and I don't know if you can do that in ES explorer.

**Comment by huanyuan** [comment]
my device has not root,project must be compiled in linux ? the windows android studio also complie,
I cannot understand this "On linux : smbclient -p 2445 //192.168.XX.XX/sharename/ -U guest%"
what is the picture content problem?
![image](https://user-images.githubusercontent.com/12406954/58391605-23ad6b80-8069-11e9-9c17-bdc19b9df69d.png)
![image](https://user-images.githubusercontent.com/12406954/58391857-01681d80-806a-11e9-942f-d04eac000d4c.png)
