### ISSUE TITLE
I want to add security to this smb server , just smb client must fill loginName and password to login,how can I do in this project? 

### ISSUE THREAD

**Issue by huanyuan** [dnbn/smbtv#5]
what is the demon  in project  about up problem?

**Comment by dnbn** [comment]
Actually it's not possible, you can just login as guest.

I started to develop this feature years ago but never finished it. If you are interested in coding it yourself, here is the code already written : https://github.com/dnbn/smbtv/tree/user_management_feature
The user list must be defined in https://github.com/dnbn/smbtv/blob/master/app/src/main/java/com/smbtv/delegate/jlan/PersistentServerConfiguration.java (initSecurityConfiguration method).

Today I'm not maintaining the app anymore since I'm not using it myself.

**Comment by huanyuan** [comment]
now this project just add database about user,the login function has no complete,The user list how to be defined in initSecurityConfiguration method?
![Screenshot_20190604-114407](https://user-images.githubusercontent.com/12406954/58851254-91d6db80-86c4-11e9-97ad-ca26648fd8cb.jpg)

**Comment by huanyuan** [comment]
now this project just add database about user,the login function has no complete,The user list how to be defined in initSecurityConfiguration method?
![image](https://user-images.githubusercontent.com/12406954/58865009-58b06280-86e8-11e9-91e0-f9a4124a8bdd.png)

**Comment by dnbn** [comment]
Yes the branch is just for the UI. 
I guess you have to add your user to the UserAccountList, something like that :
```
UserAccountList userAccounts = new UserAccountList();
UserAccount userAccount = new UserAccount(user, password);
userAccount.addUser(userAccount);
mSecurityConfig.setUserAccounts(userAccounts);
```

Then set a correct authenticator in the initCIFSConfiguration method :

```
cifsConfig.setAuthenticator("org.alfresco.jlan.server.auth.LocalAuthenticator", authenticatorCE, CifsAuthenticator.SHARE_MODE, true);
```

**Comment by huanyuan** [comment]
the correct authenticator how to write ? I had try you say but nothing effection, where I must change demon ?

 private void initSecurityConfiguration() throws InvalidConfigurationException {
        mSecurityConfig = new SecurityConfigSection(this);
        DefaultAccessControlManager accessControlManager = new DefaultAccessControlManager();
        accessControlManager.setDebug(true);
        mSecurityConfig.setAccessControlManager(DefaultAccessControlManager.class.getName(), new 
         GenericConfigElement("aclManager"));
        mSecurityConfig.setJCEProvider(CryptixCrypto.class.getName());
        final UserAccountList userAccounts = new UserAccountList();
        userAccounts.addUser(new UserAccount("admin","123456"));
        mSecurityConfig.setUserAccounts(userAccounts);
    }

  private void initCIFSConfiguration() throws InvalidConfigurationException {
        CIFSConfigSection cifsConfig = new CIFSConfigSection(this);
        SMBConfig userConfig = mSMBConfigDelegate.get();
        cifsConfig.setSessionPort(userConfig.getSessionPort());
        cifsConfig.setTcpipSMBPort(userConfig.getTcpIpSmbPort());
        cifsConfig.setNameServerPort(userConfig.getServerPort());
        cifsConfig.setDatagramPort(userConfig.getDatagramPort());
        cifsConfig.setServerName(userConfig.getHostname());
        cifsConfig.setDomainName(userConfig.getDomain());
        cifsConfig.setHostAnnounceInterval(5);
        cifsConfig.setHostAnnouncer(true);
        final GenericConfigElement authenticatorCE = new GenericConfigElement("authenticator");
        cifsConfig.setAuthenticator(SMBAuthenticator.class.getName(), authenticatorCE, CifsAuthenticator.SHARE_MODE, true);
//        cifsConfig.setAuthenticator("org.alfresco.jlan.server.auth.LocalAuthenticator", authenticatorCE,CifsAuthenticator.SHARE_MODE, true);
        cifsConfig.setHostAnnounceDebug(true);
        cifsConfig.setNetBIOSDebug(true);
        cifsConfig.setSessionDebugFlags(-1);
        cifsConfig.setTcpipSMB(true);
    }

public class SMBAuthenticator extends LocalAuthenticator {
    @Override
    public int authenticateUser(ClientInfo client, SrvSession sess, int alg) {
        return AUTH_ALLOW;
    }
}

**Comment by dnbn** [comment]
What is your error ? Did you add shares to the user account ?

I'll check when I'll have time, but you have some documentation here : https://github.com/surcloudorg/SurFS-NAS-Protocol/blob/master/alfresco-jlan/src/main/java/org/alfresco/jlan/server/auth/UserAccount.java

**Comment by huanyuan** [comment]
because SMBAuthenticator had return AUTH_ALLOW; ,so My smb client can longin without input username and password ; but I want to implemented login with input the correct password . useraccount I am ununderstand why add shares to useraccount,so I did not do this.

**Comment by dnbn** [comment]
You have to use LocalAuthenticator, not SMBAuthenticator

**Comment by huanyuan** [comment]
I had try do this before days,but cannot login with LocalAuthenticator whatever I set useraccount

**Comment by huanyuan** [comment]
a weeks I have not resolve this question, my company will fire me,please help me

**Comment by huanyuan** [comment]
cifsConfig.setAuthenticator(LocalAuthenticator.class.getName(), authenticatorCE, CifsAuthenticator.SHARE_MODE, true); 
I use this then can login whatever I input loginname and password in estrongs 
-------------------------------->>>>>>>>>>>>>>>>>>>
 cifsConfig.setAuthenticator(LocalAuthenticator.class.getName(), authenticatorCE, CifsAuthenticator.USER_MODE, true);
I use this then can not login with I get the userAccount name and password

**Comment by huanyuan** [comment]
public class SMBAuthenticator extends LocalAuthenticator {
    @Override
    public int authenticateUser(ClientInfo client, SrvSession sess, int alg) {
        UserAccount userAcc = this.getUserDetails(client.getUserName());
        if (userAcc == null){
            return AUTH_DISALLOW;
        }else {
            LogTools.d("authenticateUser====password:" + userAcc.getPassword());
            boolean authSts = false;
            if (client.getPassword() != null) {
                authSts = this.validatePassword(userAcc, client, sess.getAuthenticationContext(), alg);
            } else if (client.hasANSIPassword()) {
                authSts = this.validatePassword(userAcc, client, sess.getAuthenticationContext(), LANMAN);
            }
            return authSts ? AUTH_ALLOW : AUTH_BADPASSWORD;
        }
    }
--------------->>>>>>>>>>
I had override the LocalAuthenticator ,but still nothing effection (can login with I set useraccount name before)

**Comment by huanyuan** [comment]
public class SMBAuthenticator extends LocalAuthenticator {
@override
public int authenticateUser(ClientInfo client, SrvSession sess, int alg) {
UserAccount userAcc = this.getUserDetails(client.getUserName());
if (userAcc == null){
return AUTH_DISALLOW;
}else {
LogTools.d("authenticateUser====password:" + userAcc.getPassword());
boolean authSts = false;
if (client.getPassword() != null) {
authSts = this.validatePassword(userAcc, client, sess.getAuthenticationContext(), alg);
} else if (client.hasANSIPassword()) {
authSts = this.validatePassword(userAcc, client, sess.getAuthenticationContext(), LANMAN);
}
return authSts ? AUTH_ALLOW : AUTH_BADPASSWORD;
}
}
--------------->>>>>>>>>>
I had override the LocalAuthenticator ,but still nothing effection (can not login with I set useraccount name before)

**Comment by huanyuan** [comment]
now I had reslove thie question,thank you for your answer recently..
