### ISSUE TITLE
the smb server tcpIpSmbPort must be 2445? if my device had root ,how to make tcpIpSmbPort  can be anything

### ISSUE THREAD

**Issue by huanyuan** [dnbn/smbtv#8]

**Comment by dnbn** [comment]
If your device is root, just update all ports in the UI (menu "settings") from 2XXX to XXX.

**Comment by huanyuan** [comment]
but do this you say ,the smb client also input like 192.168.1.245:1445 ,how to  ignore （do not add :2445）endwith :1445
